# Generated by Django 2.2 on 2019-04-14 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('measurement', models.CharField(max_length=255)),
                ('orginal_price', models.PositiveIntegerField()),
                ('profit', models.PositiveIntegerField()),
                ('selling_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=255, unique=True)),
                ('contact', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=255)),
                ('quantity_r', models.PositiveIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Inventory')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Supplier'),
        ),
    ]
