# Generated by Django 2.2 on 2019-04-10 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=255, unique=True)),
                ('contact', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('measurement', models.CharField(max_length=255)),
                ('orginal_price', models.PositiveIntegerField()),
                ('profit', models.PositiveIntegerField()),
                ('selling_price', models.PositiveIntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Supplier')),
            ],
        ),
    ]
