# Generated by Django 2.2 on 2019-04-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductCostView',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'home_supplierproductcostview',
                'managed': False,
            },
        ),
    ]
